import React from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  GitCompare, 
  ArrowLeft, 
  Sparkles, 
  Sliders
} from 'lucide-react';

export const CompareDesignsPage: React.FC = () => {
  const navigate = useNavigate();

  const candidates = [
    {
      id: 'design-a',
      name: 'Design A — Passive Solar Direct Gain',
      tag: 'Recommended (Optimal)',
      tagColor: 'bg-[#2E7D4F] text-white',
      comfortScore: 92,
      heatingNeed: '18 kWh/m²/yr',
      budget: '₹ 6.35 Lakh',
      solarShare: '68%',
      wallType: '300mm Rammed Earth + 100mm EPS',
      wallU: '0.22 W/m²K',
      glazing: 'Double Low-E Argon (SHGC 0.62)',
      thermalMass: '400mm Stone Plinth + PCM Ceiling',
      payback: '3.8 Years',
      features: ['Direct south gain', 'Fast thermal response', 'Optimal budget balance']
    },
    {
      id: 'design-b',
      name: 'Design B — Heavy Trombe Mass Wall',
      tag: 'Maximum Thermal Inertia',
      tagColor: 'bg-[#6546A5] text-white',
      comfortScore: 94,
      heatingNeed: '14.5 kWh/m²/yr',
      budget: '₹ 7.10 Lakh',
      solarShare: '74%',
      wallType: '450mm Granite Trombe + Glazed Cavity',
      wallU: '0.20 W/m²K',
      glazing: 'Double Low-E Solar Control',
      thermalMass: 'Heavy Stone Trombe Wall Array',
      payback: '4.6 Years',
      features: ['12-hour thermal lag', 'Zero night cooling', 'Higher initial masonry cost']
    },
    {
      id: 'design-c',
      name: 'Design C — Eco Straw-Earth Hybrid',
      tag: 'Lowest Embodied Carbon',
      tagColor: 'bg-[#2563A9] text-white',
      comfortScore: 84,
      heatingNeed: '28.0 kWh/m²/yr',
      budget: '₹ 4.80 Lakh',
      solarShare: '54%',
      wallType: 'Straw-bale + Lime Plaster Wrap',
      wallU: '0.26 W/m²K',
      glazing: 'Double Standard Glazing',
      thermalMass: 'Sun-dried Mud Adobe Core',
      payback: '2.5 Years',
      features: ['100% locally sourced', 'Minimal machinery needed', 'Slightly higher heating demand']
    }
  ];

  return (
    <div className="p-6 lg:p-8 max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#E2E8F0] pb-5">
        <div className="flex items-center space-x-4">
          <button
            onClick={() => navigate('/results')}
            className="p-2 rounded-lg bg-white border border-[#E2E8F0] hover:bg-slate-50 text-[#64748B] hover:text-[#0B2559] transition-colors cursor-pointer"
          >
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <h1 className="text-xl font-bold text-[#0B2559] font-display flex items-center">
              <GitCompare className="w-5 h-5 mr-2 text-[#2563A9]" />
              Multi-Design Alternative Comparison
            </h1>
            <p className="text-xs text-[#64748B]">Side-by-side engineering evaluation generated by AI optimization</p>
          </div>
        </div>

        <button
          onClick={() => navigate('/what-if')}
          className="flex items-center space-x-2 px-4 py-2 rounded-xl bg-[#0B2559] hover:bg-[#2563A9] text-white text-xs font-semibold shadow-xs transition-colors cursor-pointer"
        >
          <Sliders className="w-3.5 h-3.5" />
          <span>Launch What-If Sandbox</span>
        </button>
      </div>

      {/* 3 Side-by-Side Design Cards */}
      <div className="grid md:grid-cols-3 gap-6">
        {candidates.map((cand, idx) => (
          <div
            key={cand.id}
            className={`bg-white rounded-2xl border-2 transition-all p-6 flex flex-col justify-between shadow-xs ${
              idx === 0 
                ? 'border-[#2E7D4F] ring-4 ring-[#DDF3E4]/50' 
                : 'border-[#E2E8F0] hover:border-slate-300'
            }`}
          >
            <div>
              {/* Card Header Badge */}
              <div className="flex items-center justify-between mb-4">
                <span className={`text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full font-mono ${cand.tagColor}`}>
                  {cand.tag}
                </span>
                {idx === 0 && (
                  <span className="text-[10px] font-bold text-[#2E7D4F] flex items-center">
                    <Sparkles className="w-3.5 h-3.5 mr-1" />
                    AI Choice
                  </span>
                )}
              </div>

              <h3 className="font-bold text-sm text-[#0B2559] font-display mb-4">
                {cand.name}
              </h3>

              {/* Top 3 KPI Grid */}
              <div className="grid grid-cols-3 gap-2 text-center mb-6">
                <div className="p-2 rounded-xl bg-[#F8FAFC] border border-[#E2E8F0]">
                  <p className="text-[9px] text-[#64748B] uppercase font-mono">Comfort</p>
                  <p className="text-sm font-extrabold text-[#2E7D4F] font-mono mt-0.5">{cand.comfortScore}/100</p>
                </div>
                <div className="p-2 rounded-xl bg-[#F8FAFC] border border-[#E2E8F0]">
                  <p className="text-[9px] text-[#64748B] uppercase font-mono">Heating</p>
                  <p className="text-sm font-extrabold text-[#F28C28] font-mono mt-0.5">{cand.heatingNeed.split(' ')[0]}</p>
                </div>
                <div className="p-2 rounded-xl bg-[#F8FAFC] border border-[#E2E8F0]">
                  <p className="text-[9px] text-[#64748B] uppercase font-mono">Cost</p>
                  <p className="text-sm font-extrabold text-[#0B2559] font-mono mt-0.5">{cand.budget.split(' ')[1]}</p>
                </div>
              </div>

              {/* Detailed Specs List */}
              <div className="space-y-2.5 text-xs text-[#172033] border-t border-[#E2E8F0] pt-4 mb-6">
                <div>
                  <span className="text-[#64748B] text-[11px] block">Wall Assembly:</span>
                  <span className="font-semibold">{cand.wallType}</span>
                </div>
                <div>
                  <span className="text-[#64748B] text-[11px] block">Glazing:</span>
                  <span className="font-semibold">{cand.glazing}</span>
                </div>
                <div>
                  <span className="text-[#64748B] text-[11px] block">Thermal Storage:</span>
                  <span className="font-semibold">{cand.thermalMass}</span>
                </div>
                <div>
                  <span className="text-[#64748B] text-[11px] block">Solar Gain Share:</span>
                  <span className="font-bold text-[#2563A9] font-mono">{cand.solarShare}</span>
                </div>
              </div>
            </div>

            <button
              onClick={() => navigate('/results')}
              className={`w-full py-2.5 rounded-xl font-bold text-xs transition-colors cursor-pointer ${
                idx === 0
                  ? 'bg-[#2E7D4F] hover:bg-[#256640] text-white shadow-xs'
                  : 'bg-slate-100 hover:bg-slate-200 text-[#0B2559]'
              }`}
            >
              {idx === 0 ? 'Select Recommended Design' : 'Apply Alternative Config'}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
